// Run with Playwright's browser_run_code against workspace_smoke_server.py.
async (page) => {
  const failures = [];
  const errors = [];
  const check = (ok, text) => { if (!ok) failures.push(text); };
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("http://127.0.0.1:8769/#token=workspace-preview");
  await page.evaluate(() => {
    for (const key of ["qc-workspaces-v1", "qc-workspace-chrome", "qc-appearance-v1"]) localStorage.removeItem(key);
  });
  await page.reload();
  await page.setViewportSize({ width: 1500, height: 950 });
  await page.getByRole("button", { name: /^Website redesign/ }).click();
  const ready = (count) => page.waitForFunction((count) =>
    [...document.querySelectorAll(".ws-pane:not([hidden]) .ws-pane-status")].filter((n) => n.textContent === "Ready").length === count, count);
  await ready(1);
  await page.locator('.ws-pane [data-action="h"]').click();
  await ready(2);
  const ids = await page.locator(".ws-pane").evaluateAll((nodes) => nodes.map((n) => n.dataset.pane));
  const pane = (id) => page.locator(`.ws-pane[data-pane="${id}"]`);
  const frame = (id) => pane(id).frameLocator("iframe");
  const first = frame(ids[0]), second = frame(ids[1]);
  await first.locator("#input").fill("Review the workspace manager");
  await second.locator("#input").fill("Review settings independently");
  await first.locator("#input").press("Enter");
  await second.locator("#input").press("Enter");
  await ready(2);
  await first.locator(".msg-assistant").waitFor();
  await second.locator(".msg-assistant").waitFor();
  check(!(await first.locator("#transcript").innerText()).includes("Review settings independently"), "transcripts crossed between panes");
  await second.locator("#input").fill("An unsent draft to recover");
  const documents = await page.locator(".ws-pane iframe").evaluateAll((nodes) => nodes.map((f) => {
    f.contentWindow.__workspaceSmokeMarker = Math.random();
    return f.contentWindow.__workspaceSmokeMarker;
  }));
  await pane(ids[0]).locator('[data-action="zoom"]').click();
  check(await page.locator(".ws-pane:visible").count() === 1, "zoom did not hide sibling");
  await pane(ids[0]).locator('[data-action="zoom"]').click();
  await ready(2);
  const grip = page.locator(".ws-divider").first();
  const before = await pane(ids[0]).boundingBox();
  await grip.focus(); await grip.press("ArrowRight");
  const after = await pane(ids[0]).boundingBox();
  check(after.width > before.width, "keyboard divider resize had no effect");
  check(await page.locator(".ws-divider:focus").count() === 1, "divider lost keyboard focus");
  const frameDone = () => page.evaluate(() => new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r))));
  await page.setViewportSize({ width: 1480, height: 950 }); await frameDone();
  check(await page.locator(".ws-divider:focus").count() === 1, "re-layout dropped the focused divider");
  await page.setViewportSize({ width: 1500, height: 950 }); await frameDone();
  const keyed = (await pane(ids[0]).boundingBox()).width;
  await page.locator(".ws-divider").first().press("Alt+ArrowRight");
  check((await pane(ids[0]).boundingBox()).width === keyed, "Alt+arrow on a divider also resized it");
  const handle = await page.locator(".ws-divider").first().boundingBox();
  await page.mouse.move(handle.x + handle.width / 2, handle.y + 80);
  await page.mouse.down(); await page.mouse.move(handle.x - 60, handle.y + 80); await page.mouse.up();
  check((await pane(ids[0]).boundingBox()).width < after.width, "pointer divider resize had no effect");
  await page.locator(".ws-divider").first().dblclick();
  const halves = await Promise.all(ids.map(async (id) => (await pane(id).boundingBox()).width));
  check(Math.abs(halves[0] - halves[1]) <= 1, "double-clicking a divider did not even out its panes");
  await pane(ids[0]).locator(".ws-pane-head").dragTo(pane(ids[1]).locator(".ws-pane-head"), { targetPosition: { x: 50, y: 15 } });
  check((await page.locator(".ws-pane iframe").evaluateAll((nodes) => nodes.map((f) => f.contentWindow.__workspaceSmokeMarker))).every((n, i) => n === documents[i]), "rearranging reloaded a live document");
  await page.locator("#ws-projects").click();
  await page.getByRole("button", { name: /^Client portal/ }).click();
  await ready(1);
  await page.locator(".ws-project").filter({ hasText: "Website redesign" }).click();
  await ready(2);
  check(await second.locator("#input").inputValue() === "An unsent draft to recover", "workspace switch lost draft");
  check((await page.locator(".ws-pane iframe").evaluateAll((nodes) => nodes.slice(0, 2).map((f) => f.contentWindow.__workspaceSmokeMarker))).every((n, i) => n === documents[i]), "workspace switching reloaded an agent");
  await pane(ids[1]).locator('[data-action="close"]').click();
  await ready(1);
  await page.locator("#ws-undo").click();
  await ready(2);
  check(await frame(ids[1]).locator("#input").inputValue() === "An unsent draft to recover", "reopening pane lost its draft");
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("qc-workspaces-v1")));
  await page.reload();
  await ready(2);
  check(await frame(ids[1]).locator("#input").inputValue() === "An unsent draft to recover", "reload lost draft");
  const restored = await page.evaluate(() => JSON.parse(localStorage.getItem("qc-workspaces-v1")));
  check(JSON.stringify(saved.workspaces[0].tree) === JSON.stringify(restored.workspaces[0].tree), "reload changed the split layout");
  check(saved.workspaces[0].panes[ids[0]].convId === restored.workspaces[0].panes[ids[0]].convId, "reload created a replacement conversation");
  await pane(ids[0]).locator(".ws-pane-name").click();
  await page.locator('dialog input[name="title"]').fill("Workspace review");
  await page.getByRole("button", { name: "Save name", exact: true }).click();
  await pane(ids[0]).locator(".ws-pane-name").filter({ hasText: "Workspace review" }).waitFor();
  await frame(ids[0]).locator("#btn-settings").click();
  const settings = page.frameLocator(".ws-utility iframe");
  await settings.locator("#cfg-rail").waitFor();
  await settings.getByRole("link", { name: "Appearance", exact: true }).first().click();
  await settings.locator('.theme-card[data-theme="light"]').click();
  await settings.locator("#theme-msg").filter({ hasText: "Saved" }).waitFor();
  check(await page.evaluate(() => document.documentElement.dataset.theme) === "light", "theme did not reach parent workspace");
  await settings.locator('select[name="spacing"]').selectOption("compact");
  await settings.locator('select[name="width"]').selectOption("full");
  await settings.locator('input[name="fontSize"]').fill("17");
  await settings.locator('input[name="fontSize"]').dispatchEvent("input");
  await settings.locator("#cfg-done").click();
  await page.waitForSelector(".ws-utility", { state: "detached" });
  check(await frame(ids[1]).locator("html").getAttribute("data-spacing") === "compact", "appearance did not reach other agent");
  await page.locator("#ws-help").click();
  const help = page.frameLocator(".ws-utility iframe");
  await help.getByRole("heading", { name: "Workspaces & agent panes" }).waitFor();
  await help.locator("#help-done").click();
  await page.waitForSelector(".ws-utility", { state: "detached" });
  await frame(ids[1]).locator("#input").press("Alt+z");
  await page.waitForFunction(() => [...document.querySelectorAll(".ws-pane")].filter((n) => !n.hidden).length === 1);
  check(await page.locator(".ws-pane:visible").count() === 1, "Alt+Z from composer did not zoom");
  await frame(ids[1]).locator("#input").press("Alt+z");
  await ready(2);
  await frame(ids[0]).locator("#btn-panel-toggle").click();
  await frame(ids[0]).locator('.panel-tab[data-tab="agents"]').click();
  await frame(ids[0]).locator('.panel-tab[data-tab="agents"]').click();
  check((await frame(ids[0]).locator("#main").getAttribute("class")).includes("panel-open"), "active panel tab closed panel");
  await frame(ids[0]).locator("#btn-panel-close").click();
  await page.setViewportSize({ width: 800, height: 650 });
  await pane(ids[0]).locator('[data-action="zoom"]').click();
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "workspace overflows narrow window");
  await page.locator("#ws-settings").click();
  await page.frameLocator(".ws-utility iframe").locator("#set-save").waitFor();
  check(await page.frameLocator(".ws-utility iframe").locator("#set-save").isVisible(), "settings save inaccessible in narrow window");
  await page.frameLocator(".ws-utility iframe").locator("#cfg-done").click();
  await page.setViewportSize({ width: 1500, height: 950 });
  await pane(ids[0]).locator('[data-action="zoom"]').click();
  await pane(ids[1]).locator('[data-action="h"]').click();
  await ready(3);
  await page.locator(".ws-group").filter({ hasText: "Website redesign" }).locator(".ws-manage").click();
  await page.getByRole("button", { name: "Equalize pane sizes" }).click();
  const columns = await page.locator(".ws-pane:not([hidden])").evaluateAll((nodes) => nodes.map((n) => n.getBoundingClientRect().width));
  check(Math.max(...columns) - Math.min(...columns) <= 6, `equalize left uneven columns: ${columns.join(", ")}`);
  const stored =await page.evaluate(() => Object.keys(localStorage).map((k) => [k, localStorage.getItem(k)]));
  check(stored.every(([, v]) => !v.includes("workspace-preview")), "the auth token reached localStorage");
  check(!stored.some(([k]) => k.startsWith("qc-draft")), "a draft left the tab's sessionStorage");
  // A layout this browser can no longer trust must open a fresh conversation, not a dead pane.
  const project = restored.workspaces[0].project;
  await page.evaluate((project) => localStorage.setItem("qc-workspaces-v1", JSON.stringify({ version: 1, active: project.id,
    workspaces: [{ project, focused: "__proto__", tree: { type: "pane", pane: "restored" }, panes: { restored: { convId: "bad id/.." } } }] })), project);
  await page.reload();
  await ready(1);
  if (errors.length) failures.push(...errors);
  if (failures.length) throw new Error(failures.join("\n"));
  return { passed: true, checks: "independent streams, drafts, resize, divider focus, drag, zoom, workspaces, close/undo, reload, rename, settings, themes, shortcuts, narrow layout, equalize, storage hygiene, corrupted layout", runtimeErrors: errors };
}
